### ISSUE TITLE
Not possible to remove unavailable appointments/notes

### ISSUE THREAD

**Issue by ibo549** [ibo549/calWebApp#155]
Try removing an unavailable appointment or note.  It says action failed. Check internet connection. This bug might be introduced after confirmation message.

**Comment by bszymik** [comment]
it is causing some error on webapi - so it is not related  with confirmation message

**Comment by bszymik** [comment]
confirmed, it is issue on webapi, closing this and will fix it on back-end

**Comment by Mr0K** [comment]
Bartosz, details on what was the problem exactly?

**Comment by bszymik** [comment]
while removing appointment, we were trying to remove SmsStatus object - which is null
