### ISSUE TITLE
Localization of the front-end app

### ISSUE THREAD

**Issue by ibo549** [ibo549/calWebApp#66]
- If Browser language is Polish, show Polish content otherwise English.
- Investigate storing localized strings on SPA
- Send the language preference while registration so server side can send localized e-mail. (through API method - but API method needs to be updated first)
- Change all the hardcoded strings into variables.
- Give ability to change the UI language (when changed server side needs an update too)

**Comment by ibo549** [comment]
This task only consists of localising the actual app - minus landing page.

**Comment by bszymik** [comment]
view for details of client (history) is not translated yet
