### ISSUE TITLE
Make sure that pre-loader appears before the site content

### ISSUE THREAD

**Issue by ibo549** [ibo549/calWebApp#85]
pre-loader should appear before everything is loaded and disappear when loading finishes.

**Comment by Mr0K** [comment]
I was unable to solve this problem.
Moving preloader to the very top of head section didn't make any changes to loading. 
It appears this bug appears only on firefox 5/10 times. 
Problem doesn't appear on Chrome, IE

There is an option to create a JS function, to hide body content until page loads.

To be discussed, if worth taking care of
